import Foundation

// Zero-dependency test runner (Command Line Tools have no XCTest/swift-testing).
// Each function below registers-and-runs its tests via the Harness. Run with:
//   swift run LumenTests
print("Running Lumen tests…\n")

sortOrderTests()
filterStateTests()
photoTests()
photoMetaTests()
colorLabelTests()
albumTests()
renamePatternTests()
duplicateFinderTests()
exporterTests()
metadataStoreTests()
offlineRootTests()
photoAssetTests()
imageEditorTests()
incrementalScannerTests()
importStreamingTests()
jobFailureLogTests()
volumeIdentityTests()
exifAdoptionTests()
volumeKindTests()
photosExporterTests()
exportJobTests()
reconcileCoalescingTests()
metadataHelperProtocolTests()
thumbnailCacheTests()
libraryCacheTests()
albumScaleTests()
lumenTrashTests()
crashReporterTests()
stressScanTests()
hardenedCrashFixTests()
continuationRaceTests()
folderWatcherAndSortPolishTests()
metadataAndVersionTests()
mapAndLayoutFixTests()
staleAsyncWriteGuardTests()
attributeAndFilenameFixTests()
gpsAndTimerCancelTests()
cacheDirAndHashCancelTests()
updateDedupeAndCropAspectTests()
hashAndCacheKeyTests()
crashFilenameAndIndexGuardTests()
windowReaderDedupeTests()
crashPrunePerCategoryTests()
searchDebounceAndAckTests()
folderClickExpansionTests()
dataSafetyAuditFixTests()
asyncSortCacheFixTests()
perfAuditFixTests()
bundleLocatorTests()
imageEditorOrientationTests()
thumbnailCoordinationTests()
offlineDriveGuardTests()
thumbnailSweepTests()
thumbnailPreviewAndStoreTests()
perfProbeTests()
scopePassTests()

exit(Harness.finish())
