import Foundation
@testable import LumenKit

/// Edge-case + scale checks against a synthetic library generated by
/// Scripts/make_stress_library.py: a flat many-file folder, 40-deep nesting,
/// unicode/awkward filenames, corrupt files, and symlinks INCLUDING a
/// directory loop. Catches scanner hangs (loop), duplicate ingestion
/// (followed dir symlinks), and unicode misses.
func stressScanTests() {
    // 2k keeps the default suite fast; LUMEN_STRESS_FLAT overrides for big runs.
    let flatCount = Int(ProcessInfo.processInfo.environment["LUMEN_STRESS_FLAT"] ?? "") ?? 2_000

    let root = FileManager.default.temporaryDirectory
        .appendingPathComponent("LumenStress-\(UUID().uuidString)", isDirectory: true)
    defer { try? FileManager.default.removeItem(at: root) }

    test("stressLibraryGenerates") {
        let script = URL(fileURLWithPath: #filePath)                 // …/Tests/LumenTests/StressScanTests.swift
            .deletingLastPathComponent().deletingLastPathComponent() // repo root /Tests
            .deletingLastPathComponent()
            .appendingPathComponent("Scripts/make_stress_library.py")
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/python3")
        process.arguments = [script.path, root.path, String(flatCount)]
        try process.run()
        process.waitUntilExit()
        checkEqual(process.terminationStatus, 0, "generator should succeed")
    }

    test("scanTerminatesAndCountsExactly") {
        let t0 = Date()
        let result = IncrementalScanner.scan(roots: [root], knownMtimes: [:], cachedByFolder: [:])
        let coldMs = -t0.timeIntervalSinceNow * 1000

        // flat + nested(40×3) + unicode(10) + weird(5 with image extensions)
        // + links/real.jpg. Symlinks (file aliases, dangling, dir links, the
        // loop) must contribute NOTHING — following them would duplicate the
        // flat folder wholesale and recurse until PATH_MAX on the loop.
        let expected = flatCount + 120 + 10 + 5 + 1
        checkEqual(result.photos.count, expected,
                   "scan should count exactly the real files, got \(result.photos.count)")

        let dupes = result.photos.count - Set(result.photos.map { $0.url.path }).count
        checkEqual(dupes, 0, "no path should be ingested twice")
        check(!result.photos.contains { $0.url.path.contains("/loop/") },
              "the symlink loop must not be entered")
        check(!result.photos.contains { $0.url.path.contains("/to_flat/") },
              "dir symlinks must not be followed (duplicates)")

        // Unicode names all present.
        let names = Set(result.photos.map { $0.filename })
        for name in ["한글사진.jpg", "📸🌅.jpg", "café au lait.jpg", "ＦＵＬＬＷＩＤＴＨ.jpg"] {
            check(names.contains(name), "unicode filename should be found: \(name)")
        }
        check(!names.contains("decoy.txt"), "non-image extensions stay out")
        check(!names.contains("no_extension"), "extension-less files stay out")

        // Warm rescan with the folder-mtime cache: same result, much faster.
        let byFolder = Dictionary(grouping: result.photos) { $0.folderURL.path }
        let t1 = Date()
        let warm = IncrementalScanner.scan(roots: [root], knownMtimes: result.folderMtimes,
                                           cachedByFolder: byFolder)
        let warmMs = -t1.timeIntervalSinceNow * 1000
        checkEqual(warm.photos.count, expected, "warm rescan should agree")
        print("      · stress scan flat=\(flatCount): cold \(Int(coldMs))ms · warm \(Int(warmMs))ms")
        check(coldMs < 30_000, "cold scan took \(Int(coldMs))ms")
    }
}
